[package]
authors = ["Brooks Patton <brooks@brookzerker.com>"]
edition = "2018"
name = "flocking_rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbecs = {path = "../bbecs"}
ggez = "0.5"
rand = "0.8.3"
